"""Add is_global to Supplier

Revision ID: 150a9c2fe554
Revises: b173aac8ee62
Create Date: 2026-02-26 20:31:57.384557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150a9c2fe554'
down_revision: Union[str, Sequence[str], None] = 'b173aac8ee62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_supplier_org_name_country'), 'suppliers', type_='unique')
    op.create_unique_constraint('uq_supplier_org_normalized', 'suppliers', ['organization_id', 'normalized_name', 'country'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_supplier_org_normalized', 'suppliers', type_='unique')
    op.create_unique_constraint(op.f('uq_supplier_org_name_country'), 'suppliers', ['organization_id', 'normalized_name', 'country'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
